### ISSUE TITLE
Runtime Error when trying to create a new rails app

### ISSUE THREAD

**Issue by fourcolors** [jbasdf/rails-templates#1]
Hi When i tried to make a new rails app i get this: 

rails new test_muck -m http://github.com/jbasdf/rails-templates/raw/master/muck.rb
      create  
      create  README
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
      create  app
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/mailers
      create  app/models
      create  app/views/layouts/application.html.erb
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/secret_token.rb
      create  config/initializers/session_store.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  doc
      create  doc/README_FOR_APP
      create  lib
      create  lib/tasks
      create  lib/tasks/.gitkeep
      create  log
      create  log/server.log
      create  log/production.log
      create  log/development.log
      create  log/test.log
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/favicon.ico
      create  public/index.html
      create  public/robots.txt
      create  public/images
      create  public/images/rails.png
      create  public/stylesheets
      create  public/stylesheets/.gitkeep
      create  public/javascripts
      create  public/javascripts/application.js
      create  public/javascripts/controls.js
      create  public/javascripts/dragdrop.js
      create  public/javascripts/effects.js
      create  public/javascripts/prototype.js
      create  public/javascripts/rails.js
      create  script
      create  script/rails
      create  test
      create  test/fixtures
      create  test/functional
      create  test/integration
      create  test/performance/browsing_test.rb
      create  test/test_helper.rb
      create  test/unit
      create  tmp
      create  tmp/sessions
      create  tmp/sockets
      create  tmp/cache
      create  tmp/pids
      create  vendor/plugins
      create  vendor/plugins/.gitkeep
       apply  http://github.com/jbasdf/rails-templates/raw/master/muck.rb
/Users/node/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/open-uri.rb:216:in `open_loop': redirection forbidden: http://github.com/jbasdf/rails-templates/raw/master/muck.rb -> https://github.com/jbasdf/rails-templates/raw/master/muck.rb (RuntimeError)
    from /Users/node/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/open-uri.rb:146:in`open_uri'
    from /Users/node/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/open-uri.rb:671:in `open'
    from /Users/node/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/open-uri.rb:33:in`open'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/gems/thor-0.14.6/lib/thor/actions.rb:212:in `apply'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.5/lib/rails/generators/rails/app/app_generator.rb:300:in`apply_rails_template'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/gems/thor-0.14.6/lib/thor/invocation.rb:118:in`invoke_task'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `block in invoke_all'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`each'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `map'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`invoke_all'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/gems/thor-0.14.6/lib/thor/group.rb:226:in `dispatch'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.5/lib/rails/commands/application.rb:18:in `<top (required)>'
    from /Users/node/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in`require'
    from /Users/node/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in `require'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.5/lib/rails/cli.rb:14:in`<top (required)>'
    from /Users/node/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in `require'
    from /Users/node/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in`require'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/gems/rails-3.0.5/bin/rails:4:in `<top (required)>'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/bin/rails:19:in`load'
    from /Users/node/.rvm/gems/ruby-1.9.2-p136/bin/rails:19:in `<main>'

Just thought I would show that there was run time error. Not sure if this is an issue.

**Comment by tatemae** [comment]
There is a redirect on github from http to https that messes up the template. I've updated the readme. Try it now.
